### ISSUE TITLE
Update section metadata.annotation when creating PVC using aws-efs as provisioner for storage class

### ISSUE THREAD

**Issue by palmoreck** [CONABIO/kube_sipecam#10]
In the past, the annotation volume.beta.kubernetes.io/storage-class was used instead of storageClassName attribute. This annotation is still working; however, it won't be supported in a future Kubernetes release

ref:

https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims

So, when using `aws-efs` as provisioner for storage classes needs to update section: `metadata.annotation` when creating PVC:

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs
  namespace: kubeflow
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
```
Or substitute with another provisioner (or follow suggestions of eterna2 in chat of slack of kubeflow) because

https://github.com/kubernetes-retired/external-storage/tree/master/aws/efs

looks will be retired...
